### ISSUE TITLE
Redundant imports in `database` module ?

### ISSUE THREAD

**Issue by pmoura** [terminusdb/terminusdb-server#104]
In the `database` module we have:

https://github.com/terminusdb/terminus-server/blob/c9e40f72af6c629de4f671f8b5d60e78abab5d04/library/database.pl#L35-L39

But module `triplestore` already reexports `library(terminus_store)` (with the exception of two predicates that are not called by the `database` module).

P.S. found while checking a Logtalk linter warning about the `open_memory_store/1` being imported from two different modules.

**Comment by GavinMendelGleason** [comment]
This is no longer true.
