### ISSUE TITLE
Export of a non-defined predicate, empty_context/1, in module "ask"

### ISSUE THREAD

**Issue by pmoura** [terminusdb/terminusdb-server#119]
https://github.com/terminusdb/terminus-server/blob/ccf9556f144ab2cc4f4adfd4e0dd600607cc6480/core/query/ask.pl#L8

Found while looking into a Logtalk compiler error:

```text
!     Permission error: modify uses_object_predicate empty_context/1
!       in directive use_module/2
!       in file /Users/pmoura/terminus-server/core/query.pl at or above line 94
```

The error occurs due to the `query` module using:

```logtalk
:- use_module(query/ask).
:- use_module(query/woql_compile).
```

and both `ask` and `woql_compile` modules exporting an `empty_context/1` predicate (only defined in the second module).

**Comment by GavinMendelGleason** [comment]
This should be fixed now.
