### ISSUE TITLE
README.md points to wrong latest version of project release

### ISSUE THREAD

**Issue by rahuldeepattri** [terminusdb/terminusdb-server#124]
**Describe the bug**
The README.md has a [section here](https://github.com/terminusdb/terminusdb-server#latest-version) where latest version is shown which is **v2.0.3** as of now.
The latest release points to Hotfix release which is **v1.1.3**
![image](https://user-images.githubusercontent.com/26872044/86940941-fb93a580-c160-11ea-8500-865e5b29db7a.png)

**To Reproduce**
1. Go to [here](https://github.com/terminusdb/terminusdb-server)

**Expected behavior**
Both of them should point to latest stable release which should be **v2.0.4** as of raising this issue.

**Additional context**
Shoutout to @eddiejaoude for finding this.

**Comment by eddiejaoude** [comment]
We were looking to put a link on the latest release section in the README, however, we noticed that the version stated does not match the release section on GitHub.

**Comment by rrooij** [comment]
Thanks a lot for spotting this. We used GitHub releases for some time and then stopped using it, we are now using normal git tags instead. I will remove the GitHub release as it creates confusion.

**Comment by eddiejaoude** [comment]
Sounds good 👍
