### ISSUE TITLE
Prefix not working properly when using "using"

### ISSUE THREAD

**Issue by Cheukting** [terminusdb/terminusdb-server#132]
**Describe the bug**
Prefix not working properly when using "using"

**To Reproduce**
Go to console and use "using" with prefix on the seshat dataset

**Expected behavior**
NA

**Screenshots**
NA

**Info (please complete the following information):**
 - OS: Linus
 - How did you run terminus-server: docker? 
- Gavin's set up

**Additional context**
Gavin found this bug

**Comment by GavinMendelGleason** [comment]
Prefixes should now be set in the context for the given loaded "using".
