### ISSUE TITLE
Creating huge schema results in bad performance

### ISSUE THREAD

**Issue by rrooij** [terminusdb/terminusdb-server#33]
## Steps to reproduce:

1. Use the latest terminus-server
2. Create a new database called `testdb`
3. Click in the dashboard on schema -> edit schema -> and paste the attachment in the editor
[big_turtle.ttl.txt](https://github.com/terminusdb/terminus-server/files/3766541/big_turtle.ttl.txt)
4. Save the edited schema

## Results

Terminus gets very slow. It is definitely busy indexing the schema and the like, as my CPU usage gets crazy, but the dashboard UI makes it seem like everything is finished and ready.

## Expected results

An indicator that the database is busy with indexing and the like and therefore will be slow. Or better performance for this in general. (this might be good to test again when terminus-store is implemented as storage backend)

**Comment by matko** [comment]
I created an issue in terminus-store for this: terminusdb/terminus-store#4.

**Comment by GavinMendelGleason** [comment]
This is now significantly faster.
