### ISSUE TITLE
not recovering properly from invalid document in dashboard

### ISSUE THREAD

**Issue by Anniepoo** [terminusdb/terminusdb-server#39]
1. Follow the 'my first TerminusDB' example until you have the schema
2. make a person.  Fill in the id doc:twice
and make a friend doc:nonexist

3. Click Save
EXPECTED: error message
OBSERVED: no reaction

4. click Save again
EXPECTED: ????
OBSERVED: NOW I get an error message - the message refers to the root of the document space, and generally is unhelpful

> 
> 1 Violation Detected in Document
> vio:UntypedInstanceThe subject 'http://localhost:6363/annie/document/foo' has no defined class.
> vio:subjecthttp://localhost:6363/annie/document/foo

**Comment by kevinchekovfeeney** [comment]
This no longer applies - refers to version 1.0 frame code
