### ISSUE TITLE
Non-existing database_record_schema_list/2 predicate or wrong arity?

### ISSUE THREAD

**Issue by pmoura** [terminusdb/terminusdb-server#65]
The following line calls a non-existent `database_record_schema_list/2 predicate` predicate:
 
https://github.com/terminusdb/terminus-server/blob/5f7b20c67d2fd4ccbc5dffd721669796bc883a27/library/database.pl#L272

But the `database` module exports and defines a `database_record_schema_list/3` predicate.

**Comment by GavinMendelGleason** [comment]
This is a bug in is_schema_graph/2. Really the only way to do this is to create a database. Possibly is_schema_graph/2 should be removed.

**Comment by GavinMendelGleason** [comment]
This is no longer relevant as we use a different mechanism for transaction management.
