### ISSUE TITLE
Potential inconsistency with hosted dashboard CSS

### ISSUE THREAD

**Issue by spl** [terminusdb/terminusdb-server#94]
In the process of looking at TerminusDB that led me to report https://github.com/terminusdb/terminus-dashboard/issues/15, I came across a potential problem. (I didn't find an actual instance of the problem, but I thought you might want to think about it before it becomes a problem.)

This issue is exemplified by this line in `index.tpl`:

```html
<link rel="stylesheet"
      href="https://terminusdb.github.io/terminus-dashboard/dist/css/theme.css">
```

I believe this means every local TerminusDB installation will pull down the currently released `theme.css` as found on the `gh-pages` branch in the `terminus-dashboard` repository. If I understand it correctly, this means you will need to be sure the CSS selectors in your HTML and JavaScript will need to be consistent with the ones found at the above link. Since there is no versioning of that link, this may lead to problems with different local installations.

Some possible solutions to this include:

1. releasing versions of `theme.css` and tying a server to a particular hosted version or
2. bundling the `theme.css` with the server itself.

**Comment by rrooij** [comment]
I completely agree. This was meant as a temporary measure until we have a decent process of releasing the two together.

Several options are better, I think:

* Have the terminus-dashboard as a normal subdirectory in terminus-server, tying it terminus-server (your option 2). The problem with this is that you want to use the console independently from terminus-server as well. Might be a bit of a hassle to clone terminus-server if you're only using it for a remote server.
* Have specific versions that are well tested with versions of terminus-server and linked against. To use the console offline, we could download it on the first start or let people install it using npm
* Fetch the console in a sort of installation script that will download and extract the right version for the terminus-server version that the user is installing

**Comment by spl** [comment]
> Have the terminus-dashboard as a normal subdirectory in terminus-server, tying it terminus-server (your option 2). The problem with this is that you want to use the console independently from terminus-server as well. Might be a bit of a hassle to clone terminus-server if you're only using it for a remote server.

@rrooij As a modified version of this alternative, instead of a normal subdirectory, you could use a `git` submodule, in which you specify which commit or tag of `terminus-dashboard` you require. This would allow you to continue developing the `terminus-dashboard` repository independently.

**Comment by rrooij** [comment]
We now use versioned CSS and JS for terminusdb-console (previously called terminusdb-dashboard).
